"""add is_active, author

Revision ID: 27116a83089e
Revises: 81b21e9e966e
Create Date: 2025-11-13 22:37:52.044818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27116a83089e'
down_revision = '81b21e9e966e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('author', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('author')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
